apiVersion: v1
kind: Pod
metadata:
  name: karmasandwich
spec:
  containers:
  - name: karmasandwich
    image: docker.io/maytonsw/karma_sandwich:initial
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: ks-secret